version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: school-management-db-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: school_dev
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_DB: school_management_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://school_dev:dev_password_123@postgres:5432/school_management_dev
    depends_on:
      - postgres

volumes:
  postgres_data:
